### ISSUE TITLE
Ask For An Acid

### ISSUE THREAD

**Issue by IceStarDragon707** [dotnet/docs.zh-tw#180] opened 2018-07-08 09:36 UTC
i can't figure out what is going on on this problem...
Every things work great except the very last one...
This is how it respond...

E:\APK Reverse\ILASM&gt;ilasm /dll dll.il /resource=dll.res

Microsoft (R) .NET Framework IL Assembler.  Version 2.0.50727.8922
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'dll.il'  to DLL --&gt; 'dll.dll'
Could not open dll.il

***** FAILURE *****

E:\APK Reverse\ILASM&gt;

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 64ba952e-6354-ec6b-c890-d7e22d75abd8
* Version Independent ID: ac591d0f-d67f-25a5-b100-aa48ec2d5d04
* Content: [Ilasm.exe (IL 組譯工具)](https://docs.microsoft.com/zh-tw/dotnet/framework/tools/ilasm-exe-il-assembler)
* Content Source: [docs/framework/tools/ilasm-exe-il-assembler.md](https://github.com/dotnet/docs.zh-tw/blob/live/docs/framework/tools/ilasm-exe-il-assembler.md)
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by DavidPrio** [comment] 2018-07-09 12:51
Hello, @IceStarDragon707 ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

Hi @nokura can you please investigate internally if this is Source Documentation issue or a product issue? Thanks!

**Comment by IceStarDragon707** [comment] 2018-07-09 14:40
Thanks for your help

**Comment by nokura** [comment] 2018-07-28 16:07
Hello @IceStarDragon707 
Thank you for your feedback. I am reaching out to the author to look for the solution. I will get back to you as soon as I get his input. I appreciate your patience.
Regards,
Microsoft DOCS International Team

**Comment by rpetrusha** [comment] 2018-07-30 18:37
I'm afraid that I can't reproduce this issue, @IceStarDragon707. Does the file il.dll exist, is it in the current directory, and is it a valid IL file?

**Comment by LisandroSu** [comment] 2018-08-15 15:58
Hello, @IceStarDragon707 

Thanks for your feedback. Please check the questions above.

Thanks,
Microsoft DOCS International Team

**Comment by DavidPrio** [comment] 2018-08-21 19:08
Hi @IceStarDragon707 can you please check @rpetrusha comment above? In case we do not receive more updates/info, we will consider the issue resolved and close it accordingly. Thanks for understanding.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment] 2018-08-24 17:37
Hello, @IceStarDragon707 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team

**Closed by LisandroSu** 2018-08-24 17:37 UTC
